### ISSUE TITLE
Machine Specification Reference

### ISSUE THREAD

**Issue by jimbasler-pivotal** [pivotal-cf/docs-pcf-upgrade#13]
The upgrade doc recommends "Check the required machine specifications for Ops Manager v2.5." It would be helpful to provide a link to the machine specifications. It appears the only way to find it is to go back to the install guides and dig into terraform or look it up in the manual install method.

**Comment by mlimonczenko** [comment]
Hello @jimbasler-pivotal,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
